getting data from data base
CodeYourFuture/events-calender pull request #16
Opened 2018-10-21 16:43 UTC by reber12

Adding proxy 
Getting Data from database

2018-10-21 20:32 UTC, anton-kozyr commented on backend/route/router.js
> +const app = express();
Can be removed
```suggestion
```

2018-10-21 20:33 UTC, anton-kozyr commented on backend/route/router.js
> +app.use(router);
Can be removed
```suggestion
```

2018-10-21 20:34 UTC, anton-kozyr requested changes
```app``` object is not required and can be removed

2018-10-21 22:20 UTC, anton-kozyr approved these changes

2018-10-22 10:57 UTC, dahfool commented on backend/route/router.js
>        console.log(err.stack);
@reber12 Please remove console.log.

2018-10-22 11:53 UTC, dahfool approved these changes

2018-10-22 11:53 UTC, merged