removing old styling and resizing events
CodeYourFuture/events-calender pull request #17
Opened 2018-10-22 20:01 UTC by reber12

just removing unnecessary styling

2018-10-22 22:26 UTC, dahfool commented
frontend not a very good name for the branch

2018-10-22 22:32 UTC, dahfool commented
![image](https://user-images.githubusercontent.com/4560127/47323051-2ae34580-d652-11e8-83b0-9c48d0bef9f0.png)

@reber12 
- The title should say `Events`
- The beginning of the title should be aligned with be begging of the box
- Padding inside the box should be greater, eg 20px
- Spacing between the boxes 20px
- no rounded borders.

2018-10-23 11:06 UTC, dahfool commented
@reber12 Great, i have seen the changes we need some spacing between the button and text as well. You can use bootstrap spacing for that - https://getbootstrap.com/docs/4.1/utilities/spacing/

Add this class to the button `mt-4`

2018-10-23 17:02 UTC, Behnazz commented on frontend/src/Components/Event.js
> +                    <button type="button" class="btn btn-outline-primary">
in react we should use calssName

2018-10-23 17:02 UTC, Behnazz commented on frontend/src/Components/MyForm.js
> +                <button type="button" class="btn btn-outline-primary">
change class to className

2018-10-23 17:25 UTC, dahfool approved these changes

2018-10-23 17:42 UTC, anton-kozyr commented on frontend/src/Components/Event.js
> +            <Popup trigger={<button type="button" class="btn btn-outline-primary mt-4">
use ``className``

2018-10-23 17:42 UTC, anton-kozyr requested changes
replace ```class``` with ```className```

2018-10-23 21:23 UTC, dahfool commented
@reber12 you have some conflicts.

2018-10-24 16:41 UTC, reber12 commented
> @reber12 you have some conflicts.

@dahfool sorry I can not spot conflicts

2018-10-24 21:00 UTC, anton-kozyr approved these changes

2018-10-24 21:03 UTC, merged