Nav bar
CodeYourFuture/events-calender pull request #45
Opened 2018-11-21 01:27 UTC by daleel1

nav bar
enabling floaters to register 
fixing buttons

2018-11-21 11:22 UTC, MHDGhanemBalhawan approved these changes

2018-11-25 17:29 UTC, Behnazz requested changes

2018-11-25 17:29 UTC, Behnazz commented on frontend/src/Components/Admin/Events/AdminEvents.js
> +            <div class="dummyDiv" />
`className` not `class`

2018-11-25 17:29 UTC, Behnazz commented on frontend/src/Components/Admin/Floaters/Floaters.js
> +                                    {/* <th scope="row">{floater.floater_id}</th> */}
Remove comments please

2018-11-25 17:29 UTC, Behnazz commented on frontend/src/Components/Admin/Floaters/FloatersOfEvent.js
> +                    <tbody class="table table-borderless">
ditto (`className`)

2018-11-25 17:29 UTC, Behnazz commented on frontend/src/Components/Public/AddToVolunteerList.js
> +// import VolunteerForm from "../Admin/Floaters/FloaterToVolunteer";
Remove comments

2018-11-25 17:29 UTC, Behnazz commented on frontend/src/Components/Public/AddToVolunteerList.js
> +                                        {/* <Popup
Remove comments

2018-11-25 17:29 UTC, Behnazz commented on frontend/src/Style/Events.css
> +  /* border-bottom: 1px solid rgb(41, 41, 43); */
No comments :)

2018-11-26 03:19 UTC, daleel1 commented on frontend/src/Components/Admin/Floaters/FloatersOfEvent.js
> +                    <tbody class="table table-borderless">
done

2018-11-26 03:19 UTC, daleel1 commented on frontend/src/Components/Public/AddToVolunteerList.js
> +// import VolunteerForm from "../Admin/Floaters/FloaterToVolunteer";
done

2018-11-26 03:19 UTC, daleel1 commented on frontend/src/Components/Public/AddToVolunteerList.js
> +                                        {/* <Popup
done

2018-11-26 03:20 UTC, daleel1 commented on frontend/src/Style/Events.css
> +  /* border-bottom: 1px solid rgb(41, 41, 43); */
Done @Behnazz review it please

2018-11-26 14:30 UTC, Behnazz approved these changes

2018-11-26 16:19 UTC, merged